app:
  name: "kurt-mqtt-broker"
  env: "production"

http:
  enabled: true
  host: "0.0.0.0"
  port: 18085

mqtt:
  listeners:

    - name: "tcp-public"
      protocol: "tcp"
      host: "0.0.0.0"
      port: 1883
      auth_type: "none"      # none | basic | jwt | mtls

    - name: "tls-secure"
      protocol: "tls"
      host: "0.0.0.0"
      port: 8883
      auth_type: "mtls"
      tls:
        key: "/etc/certs/server.key"
        ca: "/etc/certs/ca.crt"

    - name: "ws"
      protocol: "ws"
      host: "0.0.0.0"
      port: 8083
      auth_type: "jwt"

    - name: "wss"
      protocol: "wss"
      host: "0.0.0.0"
      port: 8084
      auth_type: "jwt"
      tls:
        cert: "/etc/certs/server.crt"
        key: "/etc/certs/server.key"